"""add genres, tags, game metadata

Revision ID: 0639bb4d14ef
Revises: 1fa50a7213cc
Create Date: 2026-06-20 13:39:23.481812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0639bb4d14ef'
down_revision: Union[str, None] = '1fa50a7213cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('game_genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appid', 'genre_id', name='uq_game_genres_appid_genre')
    )
    op.create_index(op.f('ix_game_genres_appid'), 'game_genres', ['appid'], unique=False)
    op.create_index(op.f('ix_game_genres_genre_id'), 'game_genres', ['genre_id'], unique=False)
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appid', 'tag_id', name='uq_game_tags_appid_tag')
    )
    op.create_index(op.f('ix_game_tags_appid'), 'game_tags', ['appid'], unique=False)
    op.create_index(op.f('ix_game_tags_tag_id'), 'game_tags', ['tag_id'], unique=False)
    op.add_column('games', sa.Column('rawg_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('metadata_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('rawg_match_failed', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_games_rawg_id'), 'games', ['rawg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_rawg_id'), table_name='games')
    op.drop_column('games', 'rawg_match_failed')
    op.drop_column('games', 'metadata_synced_at')
    op.drop_column('games', 'rawg_id')
    op.drop_index(op.f('ix_game_tags_tag_id'), table_name='game_tags')
    op.drop_index(op.f('ix_game_tags_appid'), table_name='game_tags')
    op.drop_table('game_tags')
    op.drop_index(op.f('ix_game_genres_genre_id'), table_name='game_genres')
    op.drop_index(op.f('ix_game_genres_appid'), table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
