"""add games, user_games, last_synced_at

Revision ID: 1fa50a7213cc
Revises: c3d50ef483c0
Create Date: 2026-06-20 11:34:47.438179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa50a7213cc'
down_revision: Union[str, None] = 'c3d50ef483c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.Column('playtime_forever', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'appid', name='uq_user_games_user_appid')
    )
    op.create_index(op.f('ix_user_games_appid'), 'user_games', ['appid'], unique=False)
    op.create_index(op.f('ix_user_games_user_id'), 'user_games', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_synced_at')
    op.drop_index(op.f('ix_user_games_user_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_appid'), table_name='user_games')
    op.drop_table('user_games')
    op.drop_table('games')
    # ### end Alembic commands ###
